# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

ports = {
    "node-1" => 4021,
    "node-2" => 4022,
}

Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"
  (1..2).each do |i|
      config.vm.define "node-#{i}" do |node|
          config.vm.provision "ansible" do |ansible|
              ansible.sudo = true
              ansible.playbook = 'playbook.yml'
          end
          node.vm.network "forwarded_port", guest: 22, host: ports["node-#{i}"], protocol: "tcp"
          node.vm.network "forwarded_port", guest: 22, host: ports["node-#{i}"], protocol: "udp"
      end
  end
end
