### Password is set to asdfasdf
- name: Create test_user
  user:
      name: test_user
      password: $6$rounds=656000$XBg/CqFDcytsP0yi$GVC0tw99djbY8Mq2iNatofS.pHqJuFX3CjVZ27/JDtOOXwI6ICe0CpoHIlllUhWiDfDB1YEpdHe/OkMGqwOQF0
      update_password: always
